require: rubocop-rails
Metrics/ClassLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
  Exclude:
    # Constrained by gem expectations
    - 'app/models/breadcrumb_trail.rb'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Rails/FindEach:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
  Include:
    - 'app/**/*'
Metrics/MethodLength:
  IgnoredMethods: ['role_permissions']
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
Metrics/BlockLength:
  Exclude:
    # BL config too long
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'
    - 'lib/tasks/*'
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Rails/DynamicFindBy:
  Whitelist:
    - find_by_alternate_identifier
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Style/MissingRespondToMissing:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/VariableNumber:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
