language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.10.6'
  - gem install rake --version '10.4.2'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libclamav-dev imagemagick libmagickcore-dev libmagic-dev redis-server libreoffice-common libimage-exiftool-perl poppler-utils
  - curl https://gist.githubusercontent.com/dgcliff/0336ad90e69f9d9b0344/raw/0aa46a8ba6b1657a48467ffd9f1b96a6176ddf86/handle_values.txt 2>/dev/null > /home/travis/build/NEU-Libraries/cerberus/config/application.yml
rvm:
  - 2.0.0
before_script:
  - "sudo service redis-server start"
cache:
  bundler: true
script: "bundle exec rake ci:build"
notifications:
  slack: neu-lts:urFXFxLoFDSvKEFdBMYDpy6v
  email:
    - d.cliff@neu.edu
    - e.zoller@neu.edu
# whitelist
branches:
  only:
    - master
    - develop
