language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickcore-dev
  - sudo apt-get install libmagic-dev
  - sudo apt-get install redis-server
  - sudo apt-get install libreoffice-common
  - sudo apt-get install clamav clamav-freshclam libclamav-dev libclamav6
rvm:
  - 2.1
before_script:
  - "sudo service redis-server start"
  - "sudo freshclam"
cache: bundler
script: "bundle exec rake ci:build"
notifications:
  slack: neu-lts:urFXFxLoFDSvKEFdBMYDpy6v
  email:
    - d.cliff@neu.edu
    - e.zoller@neu.edu
# whitelist
branches:
  only:
    - master
    - develop
