language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickcore-dev
  - sudo apt-get install libmagic-dev
rvm:
  - 2.1
before_script:
  #
cache: bundler
script: "bundle exec rake ci:build"
notifications:
  email:
    - d.cliff@neu.edu
