language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickcore-dev
  - sudo apt-get install libmagic-dev
  - sudo apt-get install redis-server
  - sudo apt-get install openoffice.org-headless
rvm:
  - 2.1
before_script:
  - "sudo service redis-server start"
cache: bundler
script: "bundle exec rake ci:build"
notifications:
  email:
    - d.cliff@neu.edu
