language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickcore-dev
  - sudo apt-get install libmagic-dev
  - sudo apt-get install redis-server
  - sudo apt-get install libreoffice-common
  - sudo apt-get install clamav clamav-freshclam libclamav-dev libclamav6
  - sudo apt-get install libimage-exiftool-perl
  - gem install bundler -v 1.10.6
  - curl https://gist.githubusercontent.com/dgcliff/0336ad90e69f9d9b0344/raw/0aa46a8ba6b1657a48467ffd9f1b96a6176ddf86/handle_values.txt 2>/dev/null > /home/travis/build/NEU-Libraries/cerberus/config/application.yml
rvm:
  - 2.1
before_script:
  - "sudo service redis-server start"
  - "sudo freshclam"
cache: bundler
script: "bundle exec rake ci:build"
notifications:
  slack: neu-lts:urFXFxLoFDSvKEFdBMYDpy6v
  email:
    - d.cliff@neu.edu
    - e.zoller@neu.edu
# whitelist
branches:
  only:
    - master
    - develop
