language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickcore-dev
  - sudo apt-get install libmagic-dev
  - sudo apt-get install redis-server
  - sudo apt-get install libreoffice-common
  - sudo apt-get install clamav clamav-freshclam libclamav-dev libclamav6
  - sudo apt-get install libimage-exiftool-perl
  # - mysql -u root < /home/travis/build/NEU-Libraries/cerberus/spec/fixtures/files/handlesTEST.sql
  # - echo 'HANDLE_USERNAME&colon; "root"\nHANDLE_PASSWORD&colon; ""\nHANDLE_HOST&colon; "localhost"\nHANDLE_DATABASE&colon; "handles"\nHANDLE_TEST_USERNAME&colon; "root"\nHANDLE_TEST_PASSWORD&colon; ""\nHANDLE_TEST_HOST&colon; "localhost"\nHANDLE_TEST_DATABASE&colon; "handles_test"' >> /home/travis/build/NEU-Libraries/cerberus/config/application.yml
rvm:
  - 2.1
before_script:
  - "sudo service redis-server start"
  - "sudo freshclam"
  - "echo \"HANDLE_USERNAME: \"root\"\nHANDLE_PASSWORD: \"\"\nHANDLE_HOST: \"localhost\"\nHANDLE_DATABASE: \"handles\"\n\" >> /home/travis/build/NEU-Libraries/cerberus/config/application.yml"
cache: bundler
script: "bundle exec rake ci:build"
notifications:
  slack: neu-lts:urFXFxLoFDSvKEFdBMYDpy6v
  email:
    - d.cliff@neu.edu
    - e.zoller@neu.edu
# whitelist
branches:
  only:
    - master
    - develop
