# Use postgres/example user/password credentials
version: '3.7'
services:
  atlas:
    volumes:
    - storage:/home/atlas/storage
  web:
    build: .
    volumes:
      - ./:/home/cerberus/web
      - storage:/home/cerberus/storage
