# Use postgres/example user/password credentials
version: '3.7'
volumes:
  solr:
  db:
  storage:
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  web:
    image: nakatomi/cerberus_web
    entrypoint: /home/cerberus/web/docker-entrypoint.sh
    ports:
      - 3000:3000
  solr:
    image: nakatomi/cerberus_solr
    ports:
    - 8983:8983
    volumes:
    - solr:/opt/solr/server/solr/mycores/blacklight-core/data
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
