development:
  host: localhost
  port: 6379
staging:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production:
  host: localhost
  port: 6379
secondary:
  host: nb4404.neu.edu
  port: 6379
