# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: http://localhost:8983/solr/development
staging:
  url: http://localhost:8080/solr/development-core
test: &TEST
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
cucumber:
  <<: *TEST
production:
  url: http://nb9477.neu.edu:8080/solr/development
secondary:
  url: http://nb9477.neu.edu:8080/solr/development
