# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: http://localhost:8983/solr/development
staging:
  url: http://solr.lib.neu.edu/solr/development
  #url: http://libtomcat.neu.edu:8080/solr/rails
test: &TEST
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
cucumber:
  <<: *TEST
production:
  url: http://your.production.server:8080/bl_solr/core0
