---
- hosts: all
  sudo: true
  tasks:
    - name: ensure epel-release
      yum: pkg=epel-release state=present

    - name: ensure packages are installed
      yum: pkg={{item}} state=present
      with_items:
        - python-devel
        - httpd
        - httpd-devel
        - libjpeg-turbo
        - libjpeg-turbo-devel
        - freetype
        - freetype-devel
        - zlib-devel
        - libtiff-devel
        - git
        - unzip
        - python-pip
        - mod_wsgi
        - libselinux-python

    - name: update pip
      shell: pip install --upgrade pip

    - name: install pip dependencies
      pip: name={{item}}
      with_items:
        - Werkzeug
        - Pillow

    - name: download kakadu
      get_url: url=http://kakadusoftware.com/wp-content/uploads/2014/06/KDU77_Demo_Apps_for_Linux-x86-64_150710.zip dest=/opt/

    - name: unzip kakadu
      unarchive: copy=no src=/opt/KDU77_Demo_Apps_for_Linux-x86-64_150710.zip dest=/opt

    - name: ensures /opt/kdu directory
      file: path=/opt/kdu state=directory

    - name: copy kakadu to /opt/kdu
      shell: cp /opt/KDU77_Demo_Apps_for_Linux-x86-64_150710/* /opt/kdu/.

    - name: ensure /etc/ld.so.conf.d/kdu.conf
      file: path=/etc/ld.so.conf.d/kdu.conf state=touch

    - name: ensure /opt/kdu is linked
      lineinfile: dest=/etc/ld.so.conf.d/kdu.conf line="/opt/kdu"

    - name: ensure /etc/profile.d/kdu.sh
      file: path=/etc/profile.d/kdu.sh state=touch

    - name: ensure kakadu command line tools are in path
      lineinfile: dest=/etc/profile.d/kdu.sh line="PATH=$PATH:/opt/kdu"

    - name: add loris user
      user: name=loris home=/var/www/loris shell=/sbin/false

    - name: git clone loris
      git: repo=https://github.com/pulibrary/loris.git dest=/opt/loris

    - name: install loris
      shell: cd /opt/loris && python setup.py install --kdu-expand /opt/kdu/kdu_expand --libkdu /opt/kdu

    - name: configure apache for loris
      copy: src=loris.conf dest=/etc/httpd/conf.d/loris.conf

    - name: ensure restart httpd
      service: name=httpd state=restarted

    - name: ensure httpd enabled
      service: name=httpd enabled=yes

    - name: ensure start firewall
      service: name=firewalld state=started

    - name: poke hole in firewall for apache
      firewalld: service=http permanent=true state=enabled immediate=yes

    - name: turn off selinux to work around mkfifo permissions issue
      selinux: state=disabled

    # Now install openseadragon demo
    - name: git clone openseadragon demo
      git: repo=https://github.com/jronallo/loris-openseadragon-demo.git dest=/opt/loris-openseadragon-demo

    - name: copy OSD files to /var/www/html/.
      shell: cp -r /opt/loris-openseadragon-demo/* /var/www/html/.

    - name: ensure /usr/local/share/images
      file: path=/usr/local/share/images state=directory

    - name: copy sample images into place
      shell: cp -r /opt/loris-openseadragon-demo/samples/* /usr/local/share/images/.
