set :domain, 'cerberusv2.library.northeastern.edu'
set :deploy_to, '/opt/cerberus'
set :repository, 'https://github.com/NEU-Libraries/cerberus.git'
set :branch, 'develop'
set :user, 'drs'
set :rails_env, 'staging'
