name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nakatomi/cerberus_web:$(cat .version)
    - name: Setup dockerize
      uses: zcong1993/setup-dockerize@v2.0.0
    - name: Start server
      run: |
        set -x
        docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - name: Create database and migrate
      run: |
        docker-compose exec -T web bundle exec rake db:create
        docker-compose exec -T web bundle exec rake db:migrate
    - name: Wait until available
      run: dockerize -wait http://localhost:3000 -timeout 1m
    - name: Run tests
      run: |
        docker-compose exec -T web bundle exec rake
